
package net.es.oscars.api.test;

import org.apache.cxf.bus.spring.SpringBusFactory;


/**
 * This class was generated by Apache CXF 2.2.1
 * Fri May 15 16:39:44 PDT 2009
 * Generated source version: 2.2.1
 * 
 */
 
public class Server{

    protected Server() throws Exception {
        System.out.println("Starting Server");
        new SpringBusFactory().createBus("file:/Users/lomax/var/oscars/OSCARSService/conf/server-cxf.xml");
        /*Object implementor = new OSCARSAuthNImpl();
        String address = "http://localhost:9090/OSCARSAuthN";
        Endpoint.publish(address, implementor);
        */
    }
    
    public static void main(String args[]) throws Exception { 
        new Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(24 * 60 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
