---
-   id:                 "junoscript"
    impl:               "net.es.oscars.pss.connect.JunoscriptConnector"
    params:
        "login":        "oscars"
        "privkeyfile":  "/home/oscars/privkeyfile"
        "passphrase":   "secret"
        "commitsync":   false

-   id:                 "clogin"
    impl:               "net.es.oscars.pss.connect.RancidConnector"
    params:
        "executable":   "/opt/rancid/clogin"
        
-   id:                 "alulogin"
    impl:               "net.es.oscars.pss.connect.RancidConnector"
    params:
        "executable":   "/opt/rancid/alulogin"
        
-   id:                 "jlogin"
    impl:               "net.es.oscars.pss.connect.RancidConnector"
    params:
        "executable":   "/opt/rancid/jlogin"

-   id:                 "openflow"
    impl:               "net.es.oscars.pss.openflowj.connect.OpenFlowJPSSConnector"