measurementArchive: http://packrat.internet2.edu:9990/perfSONAR_PS/services/SNMPMA
vlanPortNameFormat: %p.%v

node_ALBU:
    name:    mss.albu.net.internet2.edu

node_CHIC:
    name:    mss.chic.net.internet2.edu

    port_S26111:
        name: 1-A-6-1-1
    port_S27647:
        name: 1-A-7-1-1
    port_S27391:
        name: 1-A-6-1-1
    port_S27903:
        name: 1-A-8-1-1
    port_S28159:
        name: 1-A-4-1-9
    port_S28415:
        name: 1-A-5-1-1

node_LOSA:
    name:    mss.chic.net.internet2.edu

    port_S26111:
        name: 1-A-6-1-1
    port_S27647:
        name: 1-A-7-1-1
    port_S27391:
        name: 1-A-6-1-1
    port_S27903:
        name: 1-A-8-1-1
    port_S28159:
        name: 1-A-4-1-9
    port_S28415:
        name: 1-A-5-1-1


node_KANS:
    name: mss.kans.net.internet2.edu
    port_S27391: 
        name: 1-A-6-1-1

node_BOST:
    name: mss.bost.net.internet2.edu
    port_S26879: 
        name: 1-A-6-1-1

node_NEWY:
    name: mss.newy32aoa.net.internet2.edu
    port_S26367: 
        name: 1-A-5-1-1
    port_S26623:
        name: 1-A-6-1-1
    port_S27135:
        name: 1-A-3-1-3
    port_S28671:
        name: 1-A-7-1-1
    port_S27647:
        name: 1-A-3-1-5
    port_S28927:
        name: 1-A-7-1-2
    port_S28159:
        name: 1-A-4-1-1
    port_S29183:
        name: 1-A-7-1-3
    port_S29439:
        name: 1-A-7-1-4

node_WASH:
    name: mss.wash.net.internet2.edu
    port_S26111: 
        name: 1-A-5-1-3
    port_S26367:
        name: 1-A-6-1-1

node_JACK:
    name: mss.jack.net.internet2.edu
    port_S26111: 
        name: 1-A-5-1-3

node_ELPA:
    name: mss.elpa.net.internet2.edu
    port_S26367: 
        name: 1-A-5-1-3

node_HOUS:
    name: mss.hous.net.internet2.edu
    port_S26623: 
        name: 1-A-5-1-9
    port_S26879:
        name: 1-A-6-1-1

node_BATO:
    name: mss.bato.net.internet2.edu
    port_S27135: 
        name: 1-A-6-1-1

node_SUNN:
    name: mss.sunn.net.internet2.edu
    port_S26623: 
        name: 1-A-5-1-4

node_SALT:
    name: mss.salt.net.internet2.edu
    port_S26879: 
        name: 1-A-5-1-4
    port_S27647: 
        name: 1-A-7-1-1

node_LOSA:
    name: mss.losa.net.internet2.edu
    port_S27135: 
        name: 1-A-5-1-9
    port_S27391:
        name: 1-A-6-1-1

node_DENV:
    name: mss.denv.net.internet2.edu
    port_S27903: 
        name: 1-A-6-1-1

node_SEAT:
    name: mss.seat.net.internet2.edu
    port_S28159: 
        name: 1-A-6-1-1
