---

soap:
    publishTo:  'https://localhost:9050/OSCARS/PSSService'


circuitService:
    id:                 'openflow'
    stub:               true
    logRequest:         true
    logResponse:        true
    
definitions:
    models:             'defs-models.yaml'
    services:           'defs-services.yaml'


# generic impl / params config from here on
notify:
    impl:               'net.es.oscars.pss.stub.StubNotifier'
    params: 
        coordUrl:       'https://localhost:9003/OSCARS/Coord'

deviceConnectorMap:
    impl:               'net.es.oscars.pss.stub.StubDeviceConnectorMap'

deviceModelMap:
    impl:               'net.es.oscars.pss.stub.StubDeviceModelMap'

connectorDirectory:
    impl:               'net.es.oscars.pss.connect.YAMLConnectorDirectory'
    params:
        configFile:     'config-connector-directory.yaml'

deviceResolve:            
    impl:               'net.es.oscars.pss.resolve.YAMLDeviceResolver'
    params:
        configFile:     'config-device-addresses.yaml'

workflow:
    impl:               'net.es.oscars.pss.workflow.FifoWF'

validate:
    impl:               'net.es.oscars.pss.validate.SimpleValidator'
    params: 
        localDomainId:  'foo.net'

verify:
    impl:               'net.es.oscars.pss.stub.StubVerifier'
