---
- id: "juniper-t1600"
  services: 
    - id:               bridge
      configGenerator:  "net.es.oscars.pss.bridge.junos.T1600ConfigGen"
    
- id: "brocade-mlx"
  services: 
    - id:               bridge
      configGenerator:  "net.es.oscars.pss.bridge.brocade.MLXConfigGen"

- id: "alu-sr"
  services: 
    - id:               bridge
      configGenerator:  "net.es.oscars.pss.bridge.alu.SRConfigGen"
    

