---
- id: "juniper-t1600"
  services: 
    - id:               bridge
      configGenerator:  "net.es.oscars.pss.bridge.junos.T1600ConfigGen"
    
- id: "brocade-mlx"
  services: 
    - id:               bridge
      configGenerator:  "net.es.oscars.pss.bridge.brocade.MLXConfigGen"

- id: "alu-sr"
  services: 
    - id:               bridge
      configGenerator:  "net.es.oscars.pss.bridge.alu.SRConfigGen"

- id: "dell"
  services:
    - id:               bridge
      configGenerator:  "net.es.oscars.pss.bridge.generic.GenericConfigGen"
      templateConfig:
        templates:
          "SETUP":          "dell-setup.txt"
          "TEARDOWN":       "dell-teardown.txt"
          "MODIFY":         ""
          "STATUS":         ""
