---
soap:
    publishTo:  'http://localhost:9008/dijkstraPCE'
    
pce-runtime:
    url: 'http://localhost:10000/OSCARS/PCE'
    
link-evaluators:
    - class: 'net.es.oscars.pce.dijkstra.VlanLinkEvaluator'