---
soap:
    publishTo:  'https://localhost:9013/OSCARS/wsnbroker'

#authNUrl:  'http://localhost:9090/OSCARS/authN' 

#authZUrl:  'http://localhost:9190/OSCARS/authZ'

peps:
    - class: 'net.es.oscars.wsnbroker.policy.IDCEventPEP'
