package net.es.oscars.utils.sharedConstants;

public class NotifyRequestTypes {
    // Notification types
    public static String RESV_CREATE_COMPLETED  = "RESERVATION_CREATE_COMPLETED";
    public static String RESV_CREATE_FAILED  = "RESERVATION_CREATE_FAILED";
    public static String RESV_CANCEL_COMPLETED  = "RESERVATION_CANCEL_COMPLETED";  // also IDE
    public static String RESV_CANCEL_FAILED     = "RESERVATION_CANCEL_FAILED";     // also IDE
    public static String RESV_MODIFY_COMPLETED  = "RESERVATION_MODIFY_COMPLETED";
    public static String RESV_MODIFY_FAILED     = "RESERVATION_MODIFY_FAILED";
    public static String PATH_SETUP_COMPLETED = "PATH_SETUP_COMPLETED";
    public static String PATH_SETUP_FAILED = "PATH_SETUP_FAILED";
    public static String PATH_TEARDOWN_COMPLETED = "PATH_TEARDOWN_COMPLETED";
    public static String PATH_TEARDOWN_FAILED = "PATH_TEARDOWN_FAILED";
    public static String PATH_REFRESH_COMPLETED = "PATH_REFRESH_COMPLETED";
    public static String PATH_REFRESH_FAILED = "PATH_REFRESH_FAILED";
    public static String RESERVATION_PERIOD_FINISHED = "RESERVATION_PERIOD_FINISHED";
    public static String RESERVATION_EXPIRES_1DAY = "RESERVATION_EXPIRES_IN_1DAY";
    public static String RESERVATION_EXPIRES_7DAYS = "RESERVATION_EXPIRES_IN_7DAYS";
    public static String RESERVATION_EXPIRES_30DAYS = "RESERVATION_EXPIRES_IN_30DAYS";

    // InterDomainEvent types
    public static String RESV_CREATE_CONFIRMED  = "RESERVATION_CREATE_CONFIRMED";
    public static String RESV_CREATE_COMMIT_CONFIRMED  = "RESERVATION_CREATE_COMMIT_CONFIRMED";
    public static String RESV_MODIFY_COMMIT_CONFIRMED  = "RESERVATION_MODIFY_COMMIT_CONFIRMED";
    public static String RESV_MODIFY_CONFIRMED  = "RESERVATION_MODIFY_CONFIRMED";
    public static String RESV_CANCEL_CONFIRMED  = "RESERVATION_CANCEL_CONFIRMED";
    public static String RESV_CANCEL_CONFIRMED_FAILED  = "RESERVATION_CANCEL_CONFIRMED_FAILED";
    public static String PATH_SETUP_UPSTREAM_CONFIRMED     = "PATH_SETUP_UPSTREAM_CONFIRMED";
    public static String PATH_SETUP_DOWNSTREAM_CONFIRMED   = "PATH_SETUP_DOWNSTREAM_CONFIRMED";
    public static String PATH_SETUP_UPSTREAM_FAILED   = "PATH_SETUP_UPSTREAM_FAILED";
    public static String PATH_SETUP_DOWNSTREAM_FAILED   = "PATH_SETUP_DOWNSTREAM_FAILED";
    public static String PATH_TEARDOWN_UPSTREAM_CONFIRMED     = "PATH_TEARDOWN_UPSTREAM_CONFIRMED";
    public static String PATH_TEARDOWN_DOWNSTREAM_CONFIRMED   = "PATH_TEARDOWN_DOWNSTREAM_CONFIRMED";
    public static String PATH_TEARDOWN_UPSTREAM_FAILED   = "PATH_TEARDOWN_UPSTREAM_FAILED";
    public static String PATH_TEARDOWN_DOWNSTREAM_FAILED   = "PATH_TEARDOWN_DOWNSTREAM_FAILED";

}
