#!/bin/bash

MYSQL_USER="root"
MYSQL_PASSWORD=""

function print_usage(){
   echo "Usage: $0 [-u <user>] [-p] [-h] <sql-script-dir>"
   echo "   <sql-script-dir>: the directory with the sql scripts to run"
   echo "   -h: Prints this help message"
   echo "   -u <user>: MySQL user with admin privileges. Defaults to root."
   echo "   -p: Prompts for mysql password. Defaults to no password"
}

while getopts u:ph o
do    case "$o" in
          u) MYSQL_USER="$OPTARG";;
          p) printf "Enter MySQL password: "
             stty -echo
             read MYSQL_PASSWORD
             stty echo
             MYSQL_PASSWORD="-p${MYSQL_PASSWORD}";;
          h) print_usage
             exit 1;;
        [?]) print_usage
             exit 1;;
      esac
done
shift $[$OPTIND - 1]


SQL_DIR=$1
if [ -z "$SQL_DIR" ]; then
    echo "Missing sql script directory"
    print_usage
    exit 1
fi

#make sure mysql is running
status=`/etc/init.d/mysqld status | awk '{ print $NF }'`
if [ "$status" == "stopped" ]; then
    /etc/init.d/mysqld start
fi
#Determine if we need to upgrade
DB05=0
DB06=0
#Test for 0.5 tables
mysql -u $MYSQL_USER ${MYSQL_PASSWORD} --execute "SELECT id FROM users LIMIT 1" aaa > /dev/null 2>&1
if [ $? -eq 0 ]; then
    DB05=1
fi 
#Test for 0.6 tables
mysql -u $MYSQL_USER ${MYSQL_PASSWORD} --execute "SELECT id FROM users LIMIT 1" authn > /dev/null 2>&1
if [ $? -eq  0 ]; then
    DB06=1
fi

if [ $DB06 -eq 1 ]; then
    ###tables already exist - nothing to do
    exit 0
elif [ $DB05 -eq 1 ]; then
    ###upgrade tables from 0.5
    #Grant privileges and create tables
    mysql -u $MYSQL_USER ${MYSQL_PASSWORD}< $SQL_DIR/grantPrivs.sql
    if [ $? -ne 0 ]; then
        echo "WARN: Unable to create oscars user in mysql for authn"
        echo "WARN: Manually run $0 -u <mysql-root-user> -p $SQL_DIR to correct"
        exit 1
    fi
    mysql -u $MYSQL_USER ${MYSQL_PASSWORD}< $SQL_DIR/upgradeTables0.5-0.6.sql
    if [ $? -ne 0 ]; then
       echo "WARN: Unable to upgrade mysql tables from 0.5 for authn"
       echo "WARN: Manually run $0 -u <mysql-root-user> -p $SQL_DIR to correct"
       exit 1 
    fi
else
    ### no 0.5 or 0.6 tables. start from scratch.
    #Grant privileges and create tables
    mysql -u $MYSQL_USER ${MYSQL_PASSWORD}< $SQL_DIR/grantPrivs.sql
    if [ $? -ne 0 ]; then
        echo "WARN: Unable to create oscars user in mysql for authn"
        echo "WARN: Manually run $0 -u <mysql-root-user> -p $SQL_DIR to correct"
        exit 1
    fi
    mysql -u $MYSQL_USER ${MYSQL_PASSWORD}< $SQL_DIR/createTables.sql
    if [ $? -ne 0 ]; then
       echo "WARN: Unable to create mysql authn tables"
       echo "WARN: Manually run $0 -u <mysql-root-user> -p $SQL_DIR to correct"
       exit 1 
    fi
    mysql -u $MYSQL_USER ${MYSQL_PASSWORD}< $SQL_DIR/populateAttrs.sql
    if [ $? -ne 0 ]; then
       echo "WARN: Unable to populate mysql authn tables with default values"
       echo "WARN: Manually run $0 -u <mysql-root-user> -p $SQL_DIR to correct"
       exit 1
    fi
fi
