<?xml version="1.0" encoding="UTF-8"?>
<!--
    The OGF takes no position regarding the validity or scope of any intellectual property or other rights that might be claimed to pertain to the implementation or use of the technology described in this document or the extent to which any license under such rights might or might not be available; neither does it represent that it has made any effort to identify any such rights.  Copies of claims of rights made available for publication and any assurances of licenses to be made available, or the result of an attempt made to obtain a general license or permission for the use of such proprietary rights by implementers or users of this specification can be obtained from the OGF Secretariat.

    The OGF invites any interested party to bring to its attention any copyrights, patents or patent applications, or other proprietary rights which may cover technology that may be required to practice this recommendation.  Please address the information to the OGF Executive Director.

    This document and the information contained herein is provided on an "As Is" basis and the OGF disclaims all warranties, express or implied, including but not limited to any warranty that the use of the information herein will not infringe any rights or any implied warranties of merchantability or fitness for a particular purpose.

    Copyright (C) Open Grid Forum (2009-2011). All Rights Reserved.

    This document and translations of it may be copied and furnished to others, and derivative works that comment on or otherwise explain it or assist in its implementation may be prepared, copied, published and distributed, in whole or in part, without restriction of any kind, provided that the above copyright notice and this paragraph are included on all such copies and derivative works. However, this document itself may not be modified in any way, such as by removing the copyright notice or references to the OGF or other organizations, except as needed for the purpose of developing Grid Recommendations in which case the procedures for copyrights defined in the OGF Document process must be followed, or as required to translate it into languages other than English.

    The limited permissions granted above are perpetual and will not be revoked by the OGF or its successors or assignees.

    Open Grid Forum NSI Interface Discovery Protocol v2.0

    Description: This is the NSI Interface Discovery Protocol 2.0 service definitions for the reference web services implementation of the OGF NSI Interface Discovery Protocol v2.0. Comments and questions can be directed to the mailing list group mailing list (nsi-wg@ogf.org).

    This document is the SOAP endpoint definition for a provider NSA.  It holds definitions for messages the provider NSA will receive.  For the reserve, provision, release, and terminate message sets the provider will receive request messages only.  For the query operation a provider NSA must support request, confirmed, and failed messages due to the possibility that a provider NSA may query the requester for a list of connection reservations.
-->
<wsdl:definitions name="ogf_nsi_discovery_provider_v2_0"
    targetNamespace="http://schemas.ogf.org/nsi/2012/03/discovery/provider"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://schemas.ogf.org/nsi/2012/03/discovery/provider"
    xmlns:interface="http://schemas.ogf.org/nsi/2012/03/discovery/interface">

    <wsdl:import namespace="http://schemas.ogf.org/nsi/2012/03/discovery/interface"
        location="ogf_nsi_discovery_interface_v2_0.wsdl" />
  
    <!-- WSDL operation definitions with associated input (request), output
        (response), and fault (error response) messages. -->
    <wsdl:portType name="DiscoveryProviderPort">
        <wsdl:operation name="queryServices">
            <wsdl:documentation>
                This is a web services message definition of OGF NSI Interface
                Discovery protocol version 2.0 based on an HTTP/SOAP binding.
                The Interface Discovery Protocol is message based request-
                response protocol that operates between a Requester Network
                Service Agent (NSA) and a Provider NSA. The protocol is defined
                with a single operation and a generic schema to keep version
                updates to the protocol to a minimum.  There is one primitive
                supported in this version of the protocol.
                
                1. queryServices - The queryServices operation is sent from a
                Requester NSA to a Provider NSA to discover interfaces versions
                supported by the Provider NSA.  This simple request/response
                interaction uses the following messages: 
                
                queryServicesRequest contains the optional list of interface
                types the requester NSA would like returned from the provider
                NSA.  All supported interface types and versions are returned
                if the list of interface types is empty.
                
                queryServicesResponse contains the list of interface version
                information matching the request.
                
                serviceException contains exception information related to a
                failed request.
            </wsdl:documentation>
            <wsdl:input  name="queryServicesRequest"   message="interface:queryServicesRequest" />
            <wsdl:output name="queryServicesResponse"  message="interface:queryServicesResponse" />
            <wsdl:fault  name="serviceException"     message="interface:serviceException" />
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="DiscoveryProviderSoapBinding" type="tns:DiscoveryProviderPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="queryServices">
            <wsdl:documentation>
                The queryServices message is sent from a Requester NSA to a
                Provider NSA to discover interfaces versions supported by the
                Provider NSA.
                
                The Discovery service uses a basic request/response messaging 
                model with an HTTP/SOAP binding:
                - HTTP POST carries the discovery request operation
                - HTTP 200 OK response carries result of the operation
                - HTTP socket blocks until result it returned (synchronous)
            </wsdl:documentation>
            <soap:operation
                soapAction="http://schemas.ogf.org/nsi/2012/03/discovery/service/queryServices"
                style="document" />
            <wsdl:input>
                <soap:header message="interface:header" part="header" use="literal"/>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:header message="interface:header" part="header" use="literal"/>
                <soap:body use="literal" />
            </wsdl:output>
            <wsdl:fault name="serviceException">
                <soap:fault name="serviceException" use="literal" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="DiscoveryServiceProvider">
        <wsdl:port name="DiscoveryProviderPort" binding="tns:DiscoveryProviderSoapBinding">
            <soap:address location="https://localhost:8443/nsi-v2/DiscoveryServiceProvider" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
