CREATE TABLE srl (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    resource VARCHAR(100) NOT NULL,
    scope VARCHAR(100) NOT NULL,
    gri VARCHAR(100) NOT NULL,
    rangeExpr VARCHAR(100)
);

CREATE TABLE config (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    gri VARCHAR(100) NOT NULL,
    phase VARCHAR(100) NOT NULL,
    deviceId VARCHAR(100) NOT NULL,
    config TEXT NOT NULL

);
